server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Password@123


springdoc:
  writer-with-default-pretty-printer: true
  writer-with-order-by-keys: true
  swagger-ui:
    displayRequestDuration: true
    path: /swagger-ui.html
    oauth:
      appName: spring-kotlin-user-auth-postgresql
  configs:
    token-url: http://localhost:8080/oauth/token
    scopes:
      - name: ROLE_USER
        item: USER
      - name: ROLE_ADMIN
        item: ADMIN
  show-actuator: true
