name: CI

on:
  release:
    types:
      - created

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  test-stage-1:
    name: Teste Stage 1
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:                                    
          access_token: ${{ env.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Building App
        run: mvnw clean install

      - name: Unit tests
        run: mvnw test
